let bodyElement = document.getElementById("body");
console.log(bodyElement);
bodyElement.style.fontFamily="Arial, sans-serif";
bodyElement.style.backgroundColor="#f5f5f5";
bodyElement.style.display = "flex";
bodyElement.style.justifyContent="center";
bodyElement.style.alignItems="center";
bodyElement.style.height="100vh";
bodyElement.style.margin="0";
let containerElement=document.querySelector(".container");
console.log(containerElement)
containerElement.style.backgroundColor='white';
containerElement.style.border='1px solid #e0e0e0';
containerElement.style.borderRadius="8px";
containerElement.style.width="400px";
containerElement.style.textAlign="center";
containerElement.style.padding="20px";
containerElement.style.boxShadow="0 2px 4px black";
let imgElement=document.getElementById('img');
console.log(imgElement);
imgElement.style.width="80px";
imgElement.style.height="80px";
imgElement.style.marginBottom="20px";
let greetingElement=document.getElementById(".greeting");
console.log(greetingElement);
greetingElement.style.fontSize="18px";
greetingElement.style.fontWeight="bold";
greetingElement.style.color="#333";
greetingElement.style.marginBottom="10px";
let messageElement=document.getElementById(".message");
console.log(messageElement);
messageElement.style.fontSize = "14px";
messageElement.style.color="#666";
messageElement.style.marginBottom="20px";
let resetElement=document.getElementById('.reset');
console.log(resetElement);
resetElement.style.backgroundColor="#5865F2";
resetElement.style.color="white";
resetElement.style.padding="10px 20px";
resetElement.style.borderRadius="4px";
resetElement.style.fontSize="16px";
resetElement.style.cursor="pointer";
resetElement.style.marginBottom="20px";
let linksElement=document.getElementById(".links");
console.log(linksElement);
linksElement.style.fontSize="12px";
linksElement.style.color="#5865F2";
linksElement.style.marginBottom="20px";
