let bodyElement = document.getElementById("body");
console.log(bodyElement);
bodyElement.style.margin='0';
bodyElement.style.display='flex';
bodyElement.style.justifyContent='center';
bodyElement.style.alignItems='center';
bodyElement.style.height='100vh';
bodyElement.style.backgroundColor='#000';
bodyElement.style.fontFamily='Arial, sans-serif';
containerElement=document.querySelector('.container');
console.log(containerElement);
containerElement.style.width='375px';
containerElement.style.height='667px';
containerElement.style.backgroundColor='#1c2526';
containerElement.style.borderRadius='30px';
containerElement.style.position='relative';
containerElement.style.display='flex';
containerElement.style.flexDirection='column';
containerElement.style.alignItems='center';
containerElement.style.padding='20px';
containerElement.style.boxShadow='0 0 20px rgba(0, 0, 0, 0.5)';
previewElement=document.querySelector('.preview');
previewElement.style.width = '100%';
previewElement.style.height='80%';
previewElement.style.backgroundColor = '#333';
previewElement.style.borderRadius='20px';
previewElement.style.marginBottom='20px';
console.log(previewElement);
controlsElement=document.querySelector('.controls');
console.log(controlsElement);
controlsElement.style.display='flex';
controlsElement.style.justifyContent='space-around';
controlsElement.style.alignItems='center';
controlsElement.style.width='100%';
buttonElement=document.getElementById('button');
console.log(buttonElement)
buttonElement.style.width='70px';
buttonElement.style.height='70px';
buttonElement.style.backgroundColor='#fff';
buttonElement.style.border='5px solid #ccc';
buttonElement.style.borderRadius='50%';
historyElement=document.getElementById('.history');
console.log(historyElement);
historyElement.style.position='absolute';
historyElement.style.bottom='10px';
historyElement.style.fontSize='14px';